store:
    resource: "@StoreBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

stock:
    resource: "@StockBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_admin_edit:
    pattern:  /admin/stock/product/edit
    defaults: { _controller: SonataAdminBundle:CRUD:edit }

sonata_admin_custompage:
    pattern:  /admin/custompage
    defaults: { _controller: StockBundle:Product:custompage }

sonata_admin_upload:
    pattern:  /admin/upload
    defaults: { _controller: StockBundle:Product:upload }

#categories:
#    type: rest
#    resource: ApiBundle\Controller\CategoryController